name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: JDK 14 setup
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.1
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**') }}
    - name: Compile and test
      run: sbt test
  scalafmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: scalafmt-native-formatter
      uses: AvaPL/scalafmt-native-formatter@v0
