name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: JDK 14 setup
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.1
    - name: Compile and test
      run: sbt test
  scalafmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: scalafmt-native-formatter
      uses: AvaPL/scalafmt-native-formatter@v0.1.0
